### ISSUE TITLE
"Ignore case" only works if "fixed strings" param is also passed

### ISSUE THREAD

**Issue by mnahinkhan** [fethalen/better_fasta_grep#2]
Perhaps this is by design, but I think  it would be nice to mention this in the part of the help message that explains the "ignore case" flag.

Thanks for the nice project!

**Comment by fethalen** [comment]
Thank you, good catch! There was a bug in the code which caused ignore case to be ignored when fixed strings were not passed simultaneously. I've fixed this in the code and will make sure to upload the results to pip soon!
