### ISSUE TITLE
pip install broken

### ISSUE THREAD

**Issue by rattei** [fethalen/better_fasta_grep#4]
The pip install does not work anymore due to a wrongly formatted install_requires string:

`INFO: installing via PyPi:  better-fasta-grep==1.0.3
Collecting better-fasta-grep==1.0.3
  Using cached better_fasta_grep-1.0.3.tar.gz (149 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      error in better_fasta_grep setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
          setuptools>=30.3.0wheelsetuptools_scm
                    ~~~~~~~~^
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: cannot continue installation due to an error. Please check the messages above.
`

**Comment by fethalen** [comment]
Dear @rattei, thanks for opening this issue and sorry for the slow reply. There was indeed a formatting issue in the `setup.py` file. Could you install the latest version (1.0.4) and try again?

Command for installing should be:

`pip install --no-cache-dir better_fasta_grep`

**Comment by rattei** [comment]
Dear @fethalen, thanks very much for fixing this issue. Now the pip install works for me.

**Comment by fethalen** [comment]
Thanks again for noticing this and all the best!
